version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
    ports:
      - "5432:5432"

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"

  user-service:
    image: user-service:1.0
    ports:
      - "8081:8080"
    depends_on:
      - dynamodb

  task-service:
    image: task-service:2.2
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tasks
      SPRING_PROFILES_ACTIVE: local
