version: "3.8"

services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"

  user-service:
    image: user-service:1.0
    container_name: user-service
    depends_on:
      - dynamodb
    ports:
      - "8081:8080"
    environment:
      AWS_REGION: us-east-1
      DYNAMODB_ENDPOINT: http://dynamodb:8000
      SERVER_ADDRESS: 0.0.0.0
      SPRING_PROFILES_ACTIVE: local
